services:
  node:
    container_name: chubbyts-framework-skeleton-node-ci
    hostname: chubbyts-framework-skeleton-node-ci
    build:
      dockerfile: ./docker/production/node/Dockerfile
      context: ./
    environment:
      NODE_ENV: production
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '1234'
  nginx:
    container_name: chubbyts-framework-skeleton-nginx-ci
    hostname: chubbyts-framework-skeleton-nginx-ci
    image: nginx
    environment:
      SERVER_PORT: '443'
      NODE_SERVER_HOST: 'node'
      NODE_SERVER_PORT: '1234'
    ports:
      - '443:443'
    volumes:
      - ./docker/development/nginx:/etc/nginx/templates
    depends_on:
      - node
