version: '3.0'
services:
  node:
    container_name: chubbyts-framework-skeleton-node
    hostname: chubbyts-framework-skeleton-node
    build:
      dockerfile: ./docker/prod/node/Dockerfile
      context: ./
    environment:
      NODE_ENV: production
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '10080'
    ports:
      - '10080:10080'
